name: Release - Python Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-n-release:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Build package
        run: python -m build

      - name: Publish package to MORISE PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.MORISE_PYPI_USER }}
          password: ${{ secrets.MORISE_PYPI_PASS }}
          repository_url: https://mo.ri.se/pypi
      